# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OpenSourceGUI.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets


class UIOpenSourceDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(516, 350)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(160, 300, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.openSourceGroupBox = QtWidgets.QGroupBox(Dialog)
        self.openSourceGroupBox.setGeometry(QtCore.QRect(10, 10, 601, 171))
        self.openSourceGroupBox.setObjectName("groupBox")
        self.matFilesRadioButton = QtWidgets.QRadioButton(self.openSourceGroupBox)
        self.matFilesRadioButton.setGeometry(QtCore.QRect(10, 25, 91, 31))
        self.matFilesRadioButton.setChecked(True)
        self.matFilesRadioButton.setObjectName("matFilesRadioButton")
        self.matFilesRadioButton.toggled.connect(lambda: self.change_opensource_option(self.matFilesRadioButton))
        self.pointsFileRadioButton = QtWidgets.QRadioButton(self.openSourceGroupBox)
        self.pointsFileRadioButton.setGeometry(QtCore.QRect(10, 55, 101, 22))
        self.pointsFileRadioButton.setObjectName("pointsFileRadioButton")
        self.pointsFileRadioButton.toggled.connect(lambda: self.change_opensource_option(self.pointsFileRadioButton))
        self.distanceFileRadioButton = QtWidgets.QRadioButton(self.openSourceGroupBox)
        self.distanceFileRadioButton.setGeometry(QtCore.QRect(10, 85, 101, 22))
        self.distanceFileRadioButton.setObjectName("distanceFileRadioButton")
        self.distanceFileRadioButton.toggled.connect(lambda: self.change_opensource_option(self.distanceFileRadioButton))
        self.normalizationCheckButton = QtWidgets.QCheckBox(self.openSourceGroupBox)
        self.normalizationCheckButton.setEnabled(True)
        self.normalizationCheckButton.setGeometry(QtCore.QRect(10, 110, 101, 22))
        self.normalizationCheckButton.setObjectName("normalizationCheckButton")
        self.normalizationCheckButton.stateChanged.connect(self.check_normalization)
        
        
        self.matFilesLineEdit = QtWidgets.QLineEdit(self.openSourceGroupBox)
        self.matFilesLineEdit.setReadOnly(True)
        self.matFilesLineEdit.setGeometry(QtCore.QRect(110, 25, 351, 25))
        self.matFilesLineEdit.setObjectName("matFilesLineEdit")
        self.pointsFileLineEdit = QtWidgets.QLineEdit(self.openSourceGroupBox)
        self.pointsFileLineEdit.setReadOnly(True)
        self.pointsFileLineEdit.setEnabled(False)
        self.pointsFileLineEdit.setGeometry(QtCore.QRect(110, 55, 351, 25))
        self.pointsFileLineEdit.setObjectName("pointsFileLineEdit")
        self.distanceFileLineEdit = QtWidgets.QLineEdit(self.openSourceGroupBox)
        self.distanceFileLineEdit.setReadOnly(True)
        self.distanceFileLineEdit.setEnabled(False)
        self.distanceFileLineEdit.setGeometry(QtCore.QRect(110, 85, 351, 25))
        self.distanceFileLineEdit.setObjectName("distanceFileLineEdit")
        self.matFilesButton = QtWidgets.QToolButton(self.openSourceGroupBox)
        self.matFilesButton.setGeometry(QtCore.QRect(465, 25, 35, 25))
        self.matFilesButton.setObjectName("matFilesButton")
        self.matFilesButton.clicked.connect(self.open_matrices)
        self.pointsFileButton = QtWidgets.QToolButton(self.openSourceGroupBox)
        self.pointsFileButton.setEnabled(False)
        self.pointsFileButton.setGeometry(QtCore.QRect(465, 55, 35, 25))
        self.pointsFileButton.setObjectName("pointsFileButton")
        self.pointsFileButton.clicked.connect(self.open_data_file)
        self.distanceFileButton = QtWidgets.QToolButton(self.openSourceGroupBox)
        self.distanceFileButton.setEnabled(False)
        self.distanceFileButton.setGeometry(QtCore.QRect(465, 85, 35, 25))
        self.distanceFileButton.setObjectName("distanceFileButton")
        self.distanceFileButton.clicked.connect(self.open_dmatrix_file)
        
        self.dissimilarityGroupBox = QtWidgets.QGroupBox(Dialog)
        self.dissimilarityGroupBox.setGeometry(QtCore.QRect(10, 150, 491, 71))
        self.dissimilarityGroupBox.setObjectName("groupBox_2")
        self.dissimilarityBox = QtWidgets.QComboBox(self.dissimilarityGroupBox)
        self.dissimilarityBox.setGeometry(QtCore.QRect(10, 30, 471, 27))
        self.dissimilarityBox.setObjectName("dissimilarityBox")
        self.dissimilarityBox.addItem("Select...")
        self.dissimilarityBox.addItem("City-block")
        self.dissimilarityBox.addItem("Cosine-based dissimilarity")
        self.dissimilarityBox.addItem("Euclidean")
        self.dissimilarityBox.addItem("Euclidean Squared")
        self.dissimilarityBox.addItem("Extended Jaccard")
        self.dissimilarityBox.addItem("Infinity Norm")
        self.dissimilarityBox.addItem("Dynamic Time Warping (DTW)")
        self.dissimilarityBox.addItem("Max Moving Euclidean")
        self.dissimilarityBox.addItem("Min Moving Euclidean")
        self.dissimilarityBox.addItem("Mean Squared Error")
        self.dissimilarityBox.addItem("Standard Mean Squared Error")
        self.dissimilarityBox.currentIndexChanged.connect(self.change_dissimilarityBox)
        
        self.strategyGroupBox = QtWidgets.QGroupBox(Dialog)
        self.strategyGroupBox.setGeometry(QtCore.QRect(10, 220, 491, 71))
        self.strategyGroupBox.setObjectName("groupBox_3")
        self.strategyBox = QtWidgets.QComboBox(self.strategyGroupBox)
        self.strategyBox.setGeometry(QtCore.QRect(10, 40, 471, 27))
        self.strategyBox.setObjectName("strategyBox")
        self.strategyBox.addItem("Select...")
        self.strategyBox.addItem("Point by Point")
        self.strategyBox.addItem("Momenta Tree")
        self.strategyBox.addItem("Momenta AABB Tree")
        self.strategyBox.addItem("Gradient")
        self.strategyBox.currentIndexChanged.connect(self.change_strategyBox)
        
        
        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(self.accept_button)
        self.buttonBox.rejected.connect(self.cancel_button)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Open Source"))
        self.openSourceGroupBox.setTitle(_translate("Dialog", "Source"))
        self.matFilesRadioButton.setText(_translate("Dialog", "Mat Files"))
        self.pointsFileRadioButton.setText(_translate("Dialog", "Points File"))
        self.distanceFileRadioButton.setText(_translate("Dialog", "Distance File"))
        self.normalizationCheckButton.setText(_translate("Dialog", "Normalize"))
        self.matFilesButton.setText(_translate("Dialog", "..."))
        self.pointsFileButton.setText(_translate("Dialog", "..."))
        self.distanceFileButton.setText(_translate("Dialog", "..."))
        self.dissimilarityGroupBox.setTitle(_translate("Dialog", "Dissimilarity"))
        self.strategyGroupBox.setTitle(_translate("Dialog", "Strategy"))
