# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'similarityGUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class UIShell4DSimilarity_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1100, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/PhylogenyIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1100, 580))
        self.tabWidget.setObjectName("tabWidget")
        self.graphicsViewtab = QtWidgets.QWidget()
        self.graphicsViewtab.setObjectName("graphicsViewtab")
        self.lineEdit = QtWidgets.QLineEdit(self.graphicsViewtab)
        self.lineEdit.setGeometry(QtCore.QRect(942, 452, 113, 27))
        self.lineEdit.setObjectName("lineEdit")
        self.searchButton = QtWidgets.QPushButton(self.graphicsViewtab)
        self.searchButton.setGeometry(QtCore.QRect(1055, 450, 41, 31))
        self.searchButton.setObjectName("searchButton")
        self.graphicsView = QtWidgets.QGraphicsView(self.graphicsViewtab)
        self.graphicsScene = QtWidgets.QGraphicsScene()
        self.graphicsView.setScene(self.graphicsScene)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 1100, 450))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.setMouseTracking(True)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tabWidget.addTab(self.graphicsViewtab, "")
        
        self.reportsTab = QtWidgets.QWidget()
        self.reportsTab.setObjectName("reportsTab")
        self.regressionLabel = QtWidgets.QLabel(self.reportsTab)
        self.regressionLabel.setGeometry(QtCore.QRect(20, 100, 200, 27))
        self.regressionLabel.setText("Standard Error of the Estimate: ")
        self.regressionLineEdit = QtWidgets.QLineEdit(self.reportsTab)
        self.regressionLineEdit.setGeometry(QtCore.QRect(220, 100, 100, 27))
        self.regressionLineEdit.setText("0.0")
        self.tabWidget.addTab(self.reportsTab, "")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 632, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuForm = QtWidgets.QMenu(self.menubar)
        self.menuForm.setObjectName("menuForm")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen_Source = QtWidgets.QAction(MainWindow)
        self.actionOpen_Source.setObjectName("actionOpen_Source")
        self.actionOpen_Source.triggered.connect(self.open_source)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionQuit.triggered.connect(self.close_application)
        self.actionSave_Image = QtWidgets.QAction(MainWindow)
        self.actionSave_Image.setObjectName("actionSave_Image")
        self.actionSave_Image.triggered.connect(self.save_scene_image)
        self.actionSave_Data_File = QtWidgets.QAction(MainWindow)
        self.actionSave_Data_File.setObjectName("actionSave_Data_File")
        self.actionOpen_Source2 = QtWidgets.QAction(MainWindow)
        self.actionOpen_Source2.setObjectName("actionOpen_Source2")
        self.actionOpen_Source2.triggered.connect(self.open_source)
        self.actionSave_DissimilarityMatrix = QtWidgets.QAction(MainWindow)
        self.actionSave_DissimilarityMatrix.setObjectName("actionSave_DissimilarityMatrix")
        self.actionSave_DissimilarityMatrix.triggered.connect(self.save_dissimilarity_matrix)
        self.actionForce_Directed_Layout = QtWidgets.QAction(MainWindow)
        self.actionForce_Directed_Layout.setObjectName("actionForce_Directed_Layout")
        self.actionSearch_Label = QtWidgets.QAction(MainWindow)
        self.actionSearch_Label.setObjectName("actionSearch_Label")
        self.menuFile.addAction(self.actionOpen_Source)
        self.menuFile.addAction(self.actionQuit)
        self.menuForm.addAction(self.actionSave_Image)
        self.menuForm.addAction(self.actionSave_Data_File)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuForm.menuAction())
        self.toolBar.addAction(self.actionOpen_Source2)
        self.toolBar.addAction(self.actionSave_DissimilarityMatrix)
        self.toolBar.addAction(self.actionForce_Directed_Layout)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Phylogenetic Exploration"))
        self.searchButton.setIcon(QtGui.QIcon("images/icones/actions/32/search.png"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.graphicsViewtab), _translate("MainWindow", "Visualization"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reportsTab), _translate("MainWindow", "Reports"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuForm.setTitle(_translate("MainWindow", "&Save"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen_Source.setText(_translate("MainWindow", "&Open Source"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionSave_Image.setText(_translate("MainWindow", "Save &Image"))
        self.actionSave_Data_File.setText(_translate("MainWindow", "Save &Data File"))
        self.actionOpen_Source2.setText(_translate("MainWindow", "Open Source"))
        self.actionOpen_Source2.setToolTip(_translate("MainWindow", "Open Source"))
        self.actionOpen_Source2.setShortcut(_translate("MainWindow", "Shift+O"))
        self.actionOpen_Source2.setIcon(QtGui.QIcon("images/icones/actions/32/document-open.svg"))
        self.actionSave_DissimilarityMatrix.setText(_translate("MainWindow", "Save Dissimilarity Matrix"))
        self.actionSave_DissimilarityMatrix.setToolTip(_translate("MainWindow", "Save Dissimilarity Matrix"))
        self.actionSave_DissimilarityMatrix.setShortcut(_translate("MainWindow", "Shift+C"))
        self.actionSave_DissimilarityMatrix.setIcon(QtGui.QIcon("images/icones/actions/32/document-save-as.svg"))
        self.actionForce_Directed_Layout.setText(_translate("MainWindow", "Force Directed Layout"))
        self.actionForce_Directed_Layout.setToolTip(_translate("MainWindow", "Force Directed Layout"))
        self.actionForce_Directed_Layout.setShortcut(_translate("MainWindow", "Shift+F"))
        self.actionForce_Directed_Layout.setIcon(QtGui.QIcon("images/icones/actions/32/media-playback-start.svg"))
        self.actionSearch_Label.setText(_translate("MainWindow", "Search Label"))
        self.actionSearch_Label.setToolTip(_translate("MainWindow", "Search Label"))
        self.actionSearch_Label.setShortcut(_translate("MainWindow", "Shift+S"))
